# Flyway Configuration File
# https://documentation.red-gate.com/fd/configuration-parameters-149750058.html

flyway.url=jdbc:postgresql://localhost:5432/wtf_db
flyway.user=postgres
flyway.password=postgres
flyway.schemas=public
flyway.locations=filesystem:./migrations
flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true
flyway.cleanDisabled=false

